<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="FlightInformationDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAL\SQLEXPRESS;Integrated Security=True" SettingsObjectName="FlightInfoDataAccessLibrary.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblFlightInformation" Member="tblFlightInformations">
    <Type Name="tblFlightInformation">
      <Column Name="FlightNumber" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Destination" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FlightTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Airline" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>